### PR TITLE
PAAS-7923 v2.15.16

### PR DESCRIPTION
**Pull request by ronlipke**

### CODE REVIEW

**Comment by paas-api-pr-manager** [comment]
Jira Tickets included in PR are:

* [PAAS-7923](https://jira.gannett.com/browse/PAAS-7923): Pull in latest docker cookbook version
```
As a PaaS Engineer, I want to use the latest version of the docker cookbook which removes the dependency on compat-resource

Acceptance:
- Pull in git tag v2.15.16 of the docker cookbook
```

**Comment by ronlipke** [comment]
test this please

**Comment by ronlipke** [comment]
test this please

**Comment by ronlipke** [comment]
test this please

**Review by err0 — CHANGES_REQUESTED** [review]
waiting until morning

**Review by err0 — APPROVED** [review]

**Pull request merged**
